### PR TITLE
Android camera bug

### LINKED ISSUE #114: Camera crashes when opening on Android
## Expected Behavior
Camera should open and allow you to scan a QR code on android and IOS

## Actual/Current Behavior

Camera crashes on android devices when opening

### PR DESCRIPTION
**Pull request by Gjhnsn**
## Changes
_List Changes Introduced by this PR_
1. Add permissions for camera usage
2. Add placeholder screen when permissions are not enabled with instructions to enable permissions to access scanner
3. Fixed styling bug in url modals
4. Fixed folder sorting

## Purpose
So users are able to access barcode scanner through permissions.
To keep url modals looking consistent on IOS and Android
So newly edited/accessed folders are sent to the top of the list

_If this closes an issue, name it here. If it doesn't, remove this line_
Closes #114

### CODE REVIEW

**Review by connielion — APPROVED** [review]
Very noice!!!

**Review by Wolftownn — APPROVED** [review]
Nice job! Definitely gonna use for future ref.

**Review by kmausolf — COMMENTED** [review]
Did you manually update these dependencies? I just want to make sure we didn't run an `npm audit fix`

**Comment by Gjhnsn** [comment]
> 

Yes we deleted a package that we were no longer using

**Pull request merged**
